name: Build and Test

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build_and_test:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - name: Build the Docker image
        run: docker build -t microservice-boilerplate .
      - name: Run the Docker image
        run: docker run -d -p 3000:3000 --name microservice-boilerplate microservice-boilerplate
      - name: Run integration tests
        run: npm run test:integration
        env:
          APP_URL: http://localhost:3000
